[id="au-piblic-record"]
= Name change certificate

A name change certificate helps change all the other stuff (license, passport, etc.). Once it’s approved, you should move onto all the others. If you’re under 18 years old, a parent or guardian can usually do the application for you.
What you need to get a certificate varies state by state- and you must apply for the name change in the state that you were born in, or are a resident of in some cases. Sometimes you will need to submit your original birth certificate, and you’ll be issued with a new one with your new name. Otherwise, you’ll need to update that separately. The application will usually cost between 100-300 AUD to submit.

## Access Canberra

### What you need

- Ensure you have three or more identity documents.
- Complete, print and sign the application to change name for an adult or child.
- Ability to pay via card.
- Call 13 22 81 and follow the prompts.
- You will be provided with a way to submit your identity documents.

For information on where to submit your request or to find the latest information, visit the https://www.accesscanberra.act.gov.au/app/answers/detail/a_id/1936/~/change-of-name-registration#!tabs-1[ACT Government help page].


## New South Wales

Outlined here. Can be done in person or by post. Only eligible if you were born in NSW or overseas.

## Northen Territories

Outlined here. You’ll need to submit the form in person or by post. Eligible if born there or a resident.

## Queensland

Outlined here. Can only be done by post as of June 2020 (thanks to the ‘rona), but normally you can do it in person too. Only eligible if you were born in Qld or overseas.

## South Australia

Outlined here. Can only be done by post as of June 2020 (thanks to the ‘rona), but normally you can do it in person too. Eligible if born there or a resident.

## Tasmania

Outlined here. You can do it online, in person or by post. Eligible if born there or a resident.

## Victoria

Outlined here. Can be done online. Only eligible if you were born in Vic or overseas.


