[id="au-piblic-record"]
= Name change certificate

A name change certificate helps change all the other stuff (license, passport, etc.). Once it’s approved, you should move onto all the others. If you’re under 18 years old, a parent or guardian can usually do the application for you.
What you need to get a certificate varies state by state- and you must apply for the name change in the state that you were born in, or are a resident of in some cases. Sometimes you will need to submit your original birth certificate, and you’ll be issued with a new one with your new name. Otherwise, you’ll need to update that separately. The application will usually cost between 100-300 AUD to submit.

## Access Canberra

### What you need

- Ensure you have three or more identity documents.
- Complete, print and sign the application to change name for an adult or child.
- Ability to pay via card.
- Call 13 22 81 and follow the prompts.
- You will be provided with a way to submit your identity documents.

For information on where to submit your request or to find the latest information, visit the https://www.accesscanberra.act.gov.au/app/answers/detail/a_id/1936/~/change-of-name-registration#!tabs-1[ACT Government help page].


## New South Wales

https://www.nsw.gov.au/topics/name-changes-and-corrections/change-of-name[Latest information is available here] including where you can submit the documentation.
You must return all of your original certificates with your application including any:

- NSW birth certificates
- NSW change of name certificates

## Northen Territories

https://nt.gov.au/law/bdm/legal-change-of-name/legally-change-your-name[Latest information is available here] including where you can submit the documentation.
You must return all of your original certificates with your application including any:

To change your name,

- you will need to be over 18 years old and either:
- a resident of the Northern Territory (NT) for more than 12 consecutive months
- or born in the NT.

## Queensland

You can change your legal name in Queensland once every 12 months, if you are 18 or older. You can apply to change your name if you were:

- born or adopted in Queensland
- born or adopted overseas and have resided in Queensland for the past 12 months (and currently live here).

If you were born or adopted in another Australian state or territory, you need to apply to the https://www.qld.gov.au/law/births-deaths-marriages-and-divorces/birth-death-and-marriage-certificates/interstate-and-overseas-registry-offices[interstate registry office].

https://www.qld.gov.au/law/births-deaths-marriages-and-divorces/changing-your-name/changing-your-name[Latest information is available here] including where you can submit the documentation.

## South Australia
Latest information is available https://www.sa.gov.au/topics/family-and-community/births-deaths-and-marriages/changing-your-name[here]. Due to covid restrictions, information on how to submit a name change is on this page and will be updated frequently.

## Tasmania
You can register a change of name with Births, Deaths and Marriages if you were:

- born in Tasmania
- born interstate and have lived in Tasmania for more than 12 months
- born overseas, but are an Australian citizen or permanent resident and have lived in Tasmania for more than 12 months, and you are 16 years of age

https://www.justice.tas.gov.au/bdm/forms#ChangeofName[Apply] here to register your change of name.

## Victoria
Latest information on changing your name is available https://www.bdm.vic.gov.au/change-a-name[here].

## Passport
You’ll need an Australian change of name certificate, birth certificate or citizenship certificate (https://www.passports.gov.au/passports-explained/how-apply/eligibility-citizenship-and-identity/names[see here]). Note that if your current passport has at least 2 years remaining, you can get a free replacement passport with your new name.

## Gender Marker
To change your gender marker, there are several options https://www.passports.gov.au/passports-explained/how-apply/eligibility-citizenship-and-identity/sex-and-gender-diverse-passport[available]. If you use a birth certificate to prove your name change, you can change your gender marker at the same time as long as it has been on your birth certificate.

If you haven’t changed your gender on your birth certificate, the easiest method is to get a letter from a registered medical practitioner or psychologist you are receiving (gender-related) treatment from. The options for your sex marker are M, F or X. The letter from a doctor/psychologist is required if you want the X sex marker. Be aware that the X marker is not recognised in all countries and you may not be allowed to enter certain countries (the government websites are vague on which ones in particular).

