[id="au-crisis"]
= Australia


## https://qlife.org.au/[Qlife]
Australia-wide anonymous and free LGBTI peer support for people wanting to talk about sexuality, identity, gender, bodies, feelings or relationships.

Call tel:+61-1800-184-527[1800 184 527] or webchat 3pm-12am AEST.

## http://minus18.org.au/[Minus 18]
Resources help and guidance for Australia's LGBTIQ youth.

## http://www.blackrainbow.org.au/[Black Rainbow]
Australia's leading Indigenous suicide prevention and mental health support source for LGBTQ+ people.

## http://pflagaustralia.org.au/[PFLAG Australia]
Parents, Family and Friends of Lesbians and Gays.

## http://transprideaustralia.org.au/[Trans Pride Australia]
Social and support group for trans and gender diverse people and their loved ones.

## http://isupport.org.au/[Intersex Peer Support]
An intersex peer support, information and advocacy group for people born with variations in sex characteristics.

## https://ihra.org.au/[Intersex Human Rights Australia]
Support and education by and for people with intersex variation traits.

## https://headspace.org.au/[Headspace]
Australia-wide online, phone and in-person support and counselling to young people, their families and friends.

Call tel:+61-1800-650-890[1800 650 890] (9am-1am AEST).

## https://au.reachout.com/[ReachOut]
ReachOut.com helps under 25s with everyday questions through to tough times.
