[id="uk-crisis"]
= United Kingdom

== https://www.thetrevorproject.org[The Trevor Project]
If you are thinking about suicide and in need of immediate support.

=== Trevor Lifeline
tel:+1-866-488-7386[1-866-488-7386]
Available 24/7
Free

=== TrevorText
Text the word START to 678678
Standard messaging rates apply

=== TrevorChat
Enter the online portal on The Trevor Project’s website
Available 24/7
Free please call the TrevorLifeline at tel:+1-866-488-7386[1-866-488-7386] or https://www.thetrevorproject.org/get-help-now/[chat]

== https://thrivelifeline.org/index.html[THRIVE Lifeline]
If you’re experiencing a mental health crisis and need to chat with a qualified LGBTQIA+ crisis responder, our partners at THRIVE Lifeline are here for you.

THRIVE Lifeline’s experienced suicide interveners partner with oSTEM to help keep you safe during times of acute mental health crises. If you are not in an acute crisis, but are dealing with stress as you navigate identity, orientation, or barriers to academic and professional entry, THRIVE can help! Together, we are here to support your whole-self and we’re happy to help you during these troubling times.

Contact Information:
tel:+1-313-662-8209[+1 (313) 662-8209]


Available 24/7, Must be 18 years or older

== https://www.sageusa.org/what-we-do/sage-national-lgbt-elder-hotline/[SAGE]
SAGE LGBT Elder Hotline. Older LGBT people who want to talk can be connected with friendly responders who are ready to listen. If you are an LGBT elder or care for one, call the free SAGE Hotline, toll-free 24/7.

Contact information:
Toll Free
tel:+1-877-360-5428[1-877-360-LGBT (5428)]
Available 24/7

= Ireland

= Scotland

= Wales
