[id="contributing"]
= How to Contribute

## Suggesting edits online

If you think of something that can be added but don't want to get into editing docs, you can submit a suggested edit as a GitHub "issue", and one the maintainers will update the code and PDFs.
You will need a free GitHub account to make suggestions.

You can quickly create a new suggestion by filling out the form here: https://github.com/AshtonDavis/open-source-transition-resources/issues/new/choose
A suggestion "issue" is basically just an email. Please give your suggestion a title and describe how the content can be improved in the larger comment box.

## Request GitHub Project Access

Send an email to OpenSource Transition Resources Project mailing list (ccs-mod-docs@redhat.com) asking nicely to be given access to OpenSource Transition Resources Project on GitHub. Please give us your GitHub username and use the following subject line: REQUESTING ACCESS.

## Pre-requisites
STEP 1 - Asciidoc and Hugo

Install Asciidoc and Asciidoctor, the guide is written in asciidoc and published using Asciidoctor and Asciidoctor-pdf

## Configuring a Local Copy

STEP 1 - Clone the GitHub project locally:

    git clone git@github.com:AshtonDavis/open-source-transition-resources.git

STEP 2 - Verify the GitHub project status:

    cd open-source-transition-resources
    git status

STEP 3 - Enable the submodules, for the website theme

    git submodule init
    git submodule update

## Contributing Changes

STEP 1 - Create a new branch:

    git checkout -b <new_branch_name>

Example:

    git checkout -b new_edits

STEP 2 - Add content or make edits.

STEP 3 - Add and commit your changes:

    git add <path_to_file>
    git commit -m "<place_your_comments_here>"

 Example:

    git add index.adoc
    git commit -m -s "Updated the index.adoc file"

STEP 4 - Push changes to the remote GitHub repository:

    git push origin <new_branch_name>

Example:

    git push origin new_edits

STEP 5 - Create a new pull request from the GitHub web interface.

STEP 6 - Everyone on the project team will review the merge request and add comments in GitHub. This review process will be open for one week from the day the merge request was submitted. If the merge request is still being actively discussed beyond the one week timeframe, then the merge request will stay open. Once the merge request discussion is resolved, the merge request will be NACK'd or ACK'd based on the comments given.  If no comments are given after a week, then the merge request will be ACK'd.

### Configuring the Build Environment

You can build the book locally using [AsciiDoctor](http://asciidoctor.org/docs/#get-started-with-asciidoctor).

## Building the PDF's

To build and view the document locally, run the following script:

```
$ publish.sh
```
Alternatively, if you use VS Code, you can build the HTML from the "Run Menu". This will build the source docs list along with country specific docs. They are automatically placed under the website/static/guide folder. The website will link to the source pdf or the html version. Country specific pages will be available under a download link off the main page of the site.
